name: Flume Image CI
on:
  push:
    paths: 
      - flume/**
      - .github/workflows/flume-image-ci.yaml
      - build-all/**

env:
  REGISTRY: registry.cn-zhangjiakou.aliyuncs.com
  NAMESPACE: skiinder
  IMAGE: flume-github
  FLUME_VERSION: '1.10.1'
  HADOOP_VERSION: '3.3.2'
  JUICEFS_VERSION: '1.0.0-rc3'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Prepare Flume
        run: bash flume/prepare.sh
      - name: Build Image
        run: |
          TAG="${FLUME_VERSION}"
          docker login \
            --username=${{ secrets.DOCKER_USERNAME }} \
            --password=${{ secrets.DOCKER_PASSWORD }} \
            ${REGISTRY}
          cd flume
          docker build . --file Dockerfile \
            --tag ${REGISTRY}/${NAMESPACE}/${IMAGE}:${TAG} \
            --tag ${REGISTRY}/${NAMESPACE}/${IMAGE}:latest
          docker push ${REGISTRY}/${NAMESPACE}/${IMAGE}:${TAG}
          docker push ${REGISTRY}/${NAMESPACE}/${IMAGE}:latest
