name: Hbase Image CI
on:
  push:
    paths:
      - hbase/**
      - .github/workflows/hbase-image-ci.yaml
      - build-all/**

env:
  REGISTRY: registry.cn-zhangjiakou.aliyuncs.com
  NAMESPACE: skiinder
  IMAGE: hbase-github
  HBASE_VERSION: '2.4.13'
  HADOOP_VERSION: '3.3.2'
  JUICEFS_VERSION: '1.0.0-rc3'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          architecture: x64
      - name: Prepare Hbase
        run: bash hbase/prepare.sh
      - name: Upload Package
        uses: actions/upload-artifact@v3
        with:
          name: hbase-package
          path: hbase/hbase.tgz
      - name: Build Image
        run: |
          TAG="${HBASE_VERSION}"
          docker login \
            --username=${{ secrets.DOCKER_USERNAME }} \
            --password=${{ secrets.DOCKER_PASSWORD }} \
            ${REGISTRY}
          cd hbase
          docker build . --file Dockerfile \
            --tag ${REGISTRY}/${NAMESPACE}/${IMAGE}:${TAG} \
            --tag ${REGISTRY}/${NAMESPACE}/${IMAGE}:latest
          docker push ${REGISTRY}/${NAMESPACE}/${IMAGE}:${TAG}
          docker push ${REGISTRY}/${NAMESPACE}/${IMAGE}:latest