name: Hive Image CI
on:
  push:
    paths: 
      - hive/**
      - .github/workflows/hive-image-ci.yaml
      - build-all/**
  workflow_run:
    workflows: 
      - Spark Image CI
    types:
      - completed

env:
  REGISTRY: registry.cn-zhangjiakou.aliyuncs.com
  NAMESPACE: skiinder
  IMAGE: hive-github
  HIVE_VERSION: '3.1.3'
  SPARK_VERSION: '3.3.0'
  HADOOP_VERSION: '3.3.2'
  MVN_VERSION: '3.6.3'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          architecture: x64
      - name: Prepare Hive
        run: |
          bash hive/get-hadoop.sh
          bash hive/build.sh
      - name: Upload Package
        uses: actions/upload-artifact@v3
        with:
          name: hive-package
          path: hive/hive
      - name: Build Image
        run: |
          TAG="${HIVE_VERSION}"
          docker login \
            --username=${{ secrets.DOCKER_USERNAME }} \
            --password=${{ secrets.DOCKER_PASSWORD }} \
            ${REGISTRY}
          cd hive
          docker build . --file Dockerfile \
            --tag ${REGISTRY}/${NAMESPACE}/${IMAGE}:${TAG} \
            --tag ${REGISTRY}/${NAMESPACE}/${IMAGE}:latest
          docker push ${REGISTRY}/${NAMESPACE}/${IMAGE}:${TAG}
          docker push ${REGISTRY}/${NAMESPACE}/${IMAGE}:latest