name: Maxwell Image CI
on:
  push:
    paths: 
      - maxwell/**
      - .github/workflows/maxwell-image-ci.yaml
      - build-all/**

env:
  REGISTRY: registry.cn-zhangjiakou.aliyuncs.com
  NAMESPACE: skiinder
  IMAGE: maxwell-github

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build Image
        run: |
          docker login \
            --username=${{ secrets.DOCKER_USERNAME }} \
            --password=${{ secrets.DOCKER_PASSWORD }} \
            ${REGISTRY}
          cd maxwell
          docker build . --file Dockerfile \
            --tag ${REGISTRY}/${NAMESPACE}/${IMAGE}:latest
          docker push ${REGISTRY}/${NAMESPACE}/${IMAGE}:latest